namespace Raider.Metrics
{
	public enum EventCounterEnum
	{
		SystemRuntimeCpuUsage = 1,
		SystemRuntimeWorkingSet = 2,
		SystemRuntimeGcHeapSize = 3,
		SystemRuntimeGen0GcCount = 4,
		SystemRuntimeGen1GcCount = 5,
		SystemRuntimeGen2GcCount = 6,
		SystemRuntimeThreadpoolThreadCount = 7,
		SystemRuntimeMonitorLockContentionCount = 8,
		SystemRuntimeThreadpoolQueueLength = 9,
		SystemRuntimeThreadpoolCompletedItemsCount = 10,
		SystemRuntimeAllocRate = 11,
		SystemRuntimeActiveTimerCount = 12,
		SystemRuntimeGcFragmentation = 13,
		SystemRuntimeExceptionCount = 14,
		SystemRuntimeTimeInGc = 15,
		SystemRuntimeGen0Size = 16,
		SystemRuntimeGen1Size = 17,
		SystemRuntimeGen2Size = 18,
		SystemRuntimeLohSize = 19,
		SystemRuntimePohSize = 20,
		SystemRuntimeAssemblyCount = 21,
		SystemRuntimeIlBytesJitted = 22,
		SystemRuntimeMethodsJittedCount = 23,
		MicrosoftAspNetCoreHostingCurrentRequests = 24,
		MicrosoftAspNetCoreHostingFailedRequests = 25,
		MicrosoftAspNetCoreHostingRequestsPerSecond = 26,
		MicrosoftAspNetCoreHostingTotalRequests = 27,
		MicrosoftAspNetCoreHttpConnectionsConnectionsDuration = 28,
		MicrosoftAspNetCoreHttpConnectionsCurrentConnections = 29,
		MicrosoftAspNetCoreHttpConnectionsConnectionsStarted = 30,
		MicrosoftAspNetCoreHttpConnectionsConnectionsStopped = 31,
		MicrosoftAspNetCoreHttpConnectionsConnectionsTimedOut = 32,
		MicrosoftAspNetCoreServerKestrelConnectionsPerSecond = 33,
		MicrosoftAspNetCoreServerKestrelTlsHandshakesPerSecond = 34,
		MicrosoftAspNetCoreServerKestrelTotalConnections = 35,
		MicrosoftAspNetCoreServerKestrelTotalTlsHandshakes = 36,
		MicrosoftAspNetCoreServerKestrelCurrentTlsHandshakes = 37,
		MicrosoftAspNetCoreServerKestrelFailedTlsHandshakes = 38,
		MicrosoftAspNetCoreServerKestrelCurrentConnections = 39,
		MicrosoftAspNetCoreServerKestrelConnectionQueueLength = 40,
		MicrosoftAspNetCoreServerKestrelRequestQueueLength = 41,
		MicrosoftAspNetCoreServerKestrelCurrentUpgradedRequests = 42,
		SystemNetHttpRequestsStartedRate = 43,
		SystemNetHttpRequestsFailedRate = 44,
		SystemNetHttpRequestsStarted = 45,
		SystemNetHttpRequestsFailed = 46,
		SystemNetHttpCurrentRequests = 47,
		SystemNetHttpHttp11ConnectionsCurrentTotal = 48,
		SystemNetHttpHttp20ConnectionsCurrentTotal = 49,
		SystemNetHttpHttp11RequestsQueueDuration = 50,
		SystemNetHttpHttp20RequestsQueueDuration = 51
	}
}
