// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Raider.Generator.Compilation
{
    using Raider.Extensions;
    using System.IO;
    using System.Linq;
    using System.Reflection;
    using System.Resources;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ResourcesGenerator : GeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 11 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"

	SetGenerationEnvironment(this.GenerationEnvironment);
	
	string targetProject = GetParam("TargetProject");
	string nmspace = GetParam("RootNamespace");
    var resFiles = GetParam<List<Raider.Localization.ResourceFile>>("ResFiles");
    var resourcesClassName = GetParam("ResourcesClassName");
		
	StartNewFile(Path.Combine(targetProject, "Configuration"), resourcesClassName + ".cs");

            
            #line default
            #line hidden
            this.Write(@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ");
            
            #line 30 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nmspace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic static partial class Resources\r\n\t{\r\n\t\tprivate static ResourcesManage" +
                    "r _resMan;\r\n\t\tpublic static ResourcesManager ResourcesManager\r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{" +
                    "\r\n\t\t\t\treturn _resMan ?? (_resMan = new ResourcesManager(typeof(");
            
            #line 39 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nmspace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 39 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resourcesClassName));
            
            #line default
            #line hidden
            this.Write(").Assembly));\r\n\t\t\t}\r\n\t\t}\r\n\t}\r\n}\r\n");
            
            #line 44 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"

	
	foreach (var resFile in resFiles)
	{
		var resStructure = resFile.GetConfigurationFolderStructure(targetProject);
		var resPath = resFile.GetConfigurationFolderPath("Configuration", targetProject);
		StartNewFile(resPath, resFile.Name + "Resource.cs");
		
		int ident = 0;


            
            #line default
            #line hidden
            this.Write(@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ");
            
            #line 64 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nmspace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 66 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"

		foreach (var parentClass in resStructure)
		{

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 70 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident)));
            
            #line default
            #line hidden
            this.Write("public static partial class ");
            
            #line 70 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parentClass));
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 71 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident)));
            
            #line default
            #line hidden
            this.Write("{\r\n");
            
            #line 72 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"

			ident++;
		}
		string className = resFile.Name.ToCammelCase(removeUnderscores: false);

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 77 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident)));
            
            #line default
            #line hidden
            this.Write("public static partial class ");
            
            #line 77 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 78 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident)));
            
            #line default
            #line hidden
            this.Write("{\r\n\t");
            
            #line 79 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("public static readonly System.Collections.Generic.IReadOnlyDictionary<string, Sys" +
                    "tem.Func<string>> Dictionary = new System.Collections.Generic.Dictionary<string," +
                    " System.Func<string>>\r\n\t");
            
            #line 80 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("{\r\n");
            
            #line 81 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"

				int resCount = 0;
                foreach (var resource in resFile)
				{
					if (resource.Parameters.Count == 0)
					{

            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 88 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("{ nameof(");
            
            #line 88 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resource.Name.ToCammelCase(removeUnderscores: false)));
            
            #line default
            #line hidden
            this.Write("), () => ");
            
            #line 88 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resource.Name.ToCammelCase(removeUnderscores: false)));
            
            #line default
            #line hidden
            this.Write(" },\r\n");
            
            #line 89 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"

					}
					else
					{

            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 94 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("{ nameof(");
            
            #line 94 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resource.Name.ToCammelCase(removeUnderscores: false)));
            
            #line default
            #line hidden
            this.Write("), () => ");
            
            #line 94 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resource.Name.ToCammelCase(removeUnderscores: false)));
            
            #line default
            #line hidden
            this.Write("_Message },\r\n");
            
            #line 95 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"

					}
				}

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 99 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("};\r\n\r\n");
            
            #line 101 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"

                foreach (var resource in resFile)
                {
					if (string.IsNullOrWhiteSpace(resource.Value))
					{
						throw new InvalidOperationException("Resource " + resFile.FullPath + " has invalid value for name " + resource.Name);
					}

                    if (0 < resCount)
                    {

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 113 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"

                    }

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 116 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("/// <summary>\r\n");
            
            #line 117 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"

					var valueLines = Lines(resource.Value);
					foreach (var line in valueLines)
					{

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 122 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("/// ");
            
            #line 122 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Xml(line)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 123 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"

					}

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 126 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("/// </summary>\r\n");
            
            #line 127 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"

					if (resource.Parameters.Any())
					{

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 131 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("public static string ");
            
            #line 131 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resource.Name.ToCammelCase(removeUnderscores: false)));
            
            #line default
            #line hidden
            this.Write("_Message\r\n\t");
            
            #line 132 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 2)));
            
            #line default
            #line hidden
            this.Write("=> ResourcesManager.GetString(\"");
            
            #line 132 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resFile.GetResourceRelativeName(resourcesClassName)));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 132 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resource.Name));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 132 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(" ", valueLines)));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\r\n\t");
            
            #line 134 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("/// <summary>\r\n");
            
            #line 135 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"

					valueLines = Lines(resource.Value);
					foreach (var line in valueLines)
					{

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 140 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("/// ");
            
            #line 140 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Xml(line)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 141 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"

					}

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 144 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("/// </summary>\r\n\t");
            
            #line 145 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("public static string ");
            
            #line 145 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resource.Name.ToCammelCase(removeUnderscores: false)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 145 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(List("object p", resource.Parameters)));
            
            #line default
            #line hidden
            this.Write(", string defaultValue = \"");
            
            #line 145 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(" ", valueLines)));
            
            #line default
            #line hidden
            this.Write("\")\r\n\t");
            
            #line 146 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 2)));
            
            #line default
            #line hidden
            this.Write("=> string.Format(\r\n\t");
            
            #line 147 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 3)));
            
            #line default
            #line hidden
            this.Write("ResourcesManager.GetString(\"");
            
            #line 147 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resFile.GetResourceRelativeName(resourcesClassName)));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 147 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resource.Name));
            
            #line default
            #line hidden
            this.Write("\", defaultValue),\r\n\t");
            
            #line 148 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 3)));
            
            #line default
            #line hidden
            
            #line 148 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(List("p", resource.Parameters)));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 149 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"

					}
					else
					{

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 154 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("public static string ");
            
            #line 154 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resource.Name.ToCammelCase(removeUnderscores: false)));
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 155 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 2)));
            
            #line default
            #line hidden
            this.Write("=> ResourcesManager.GetString(\"");
            
            #line 155 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resFile.GetResourceRelativeName(resourcesClassName)));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 155 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resource.Name));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 155 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(" ", valueLines)));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 156 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"

					}
					resCount++;
                }

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 161 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident)));
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 162 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"


		for (int i = resStructure.Count - 1; 0 <= i; i--)
		{

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 167 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(i)));
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 168 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 172 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"

	}
	Process();

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 176 "C:\Code\GitLab\Raider\src\Raider.Generator.Compilation\ResourcesGenerator.tt"

	private string GetIdent(int count)
	{
		return GetIdent(null, count);
	}

	private string GetIdent(string baseIdent, int count)
	{
		StringBuilder sb = new StringBuilder(baseIdent ?? "");
		for (int i = 0; i < count; i++)
		{
			sb.Append("\t");
		}
		return sb.ToString();
	}

    private IEnumerable<string> Lines(string value)
    {
        return value.Split(new[] { Environment.NewLine }, StringSplitOptions.None);
    }

    private string Xml(string value)
    {
        return value.Replace("<", "&lt;").Replace(">", "&gt;");
    }

    private string List(IEnumerable<string> items)
    {
        return List(null, items);
    }

    private string List(string prefix, IEnumerable<string> items, string suffix = null)
    {
        return string.Join(", ", items.Select(i => prefix + i + suffix));
    }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
