// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Raider.Generator.Compilation
{
    using Raider.Extensions;
    using System.IO;
    using System.Linq;
    using System.Reflection;
    using System.Resources;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ResourceKeysGenerator : GeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 11 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"

	SetGenerationEnvironment(this.GenerationEnvironment);
	
	string targetProject = GetParam("TargetProject");
	string nmspace = GetParam("RootNamespace");
	var resFiles = GetParam<List<Raider.Localization.ResourceFile>>("ResFiles");
	
	foreach (var resFile in resFiles)
	{
		var resStructure = resFile.GetConfigurationFolderStructure(targetProject);
		var resPath = resFile.GetConfigurationFolderPath(null, targetProject);
		StartNewFile(resPath, resFile.Name + "ResourceKeys.cs");
		
		int ident = 0;


            
            #line default
            #line hidden
            this.Write(@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ");
            
            #line 36 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nmspace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 38 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"

		foreach (var parentClass in resStructure)
		{

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 42 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident)));
            
            #line default
            #line hidden
            this.Write("public partial class ");
            
            #line 42 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parentClass));
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 43 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident)));
            
            #line default
            #line hidden
            this.Write("{\r\n");
            
            #line 44 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"

			ident++;
		}
		string className = resFile.Name.ToCSharpClassNameConvention(removeUnderscores: false);

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 49 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident)));
            
            #line default
            #line hidden
            this.Write("public partial class ");
            
            #line 49 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("Keys\r\n\t");
            
            #line 50 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident)));
            
            #line default
            #line hidden
            this.Write("{\r\n\t\t\tpublic const string __BaseName = \"");
            
            #line 51 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resPath.TrimPrefix(targetProject).Replace(System.IO.Path.DirectorySeparatorChar, '.')));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 51 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resFile.Name));
            
            #line default
            #line hidden
            this.Write("\";\r\n\r\n");
            
            #line 53 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"

				int resCount = 0;
				foreach (var resource in resFile)
				{
					if (string.IsNullOrWhiteSpace(resource.Value))
					{
						throw new InvalidOperationException("Resource " + resFile.FullPath + " has invalid value for name " + resource.Name);
					}

					if (0 < resCount)
					{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 66 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"

					}

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 69 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("public const string ");
            
            #line 69 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resource.Name.ToCSharpClassNameConvention(removeUnderscores: false)));
            
            #line default
            #line hidden
            this.Write(" = \"");
            
            #line 69 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resource.Name));
            
            #line default
            #line hidden
            this.Write("\";\r\n");
            
            #line 70 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"

					resCount++;
				}

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 74 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident)));
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 75 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"


		for (int i = resStructure.Count - 1; 0 <= i; i--)
		{

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 80 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(i)));
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 81 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 85 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"

	}
	Process();

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 89 "C:\Code\GitLab\H\FWK\src\Raider.Generator.Compilation\ResourceKeysGenerator.tt"

	private string GetIdent(int count)
	{
		return GetIdent(null, count);
	}

	private string GetIdent(string baseIdent, int count)
	{
		StringBuilder sb = new StringBuilder(baseIdent ?? "");
		for (int i = 0; i < count; i++)
		{
			sb.Append("\t");
		}
		return sb.ToString();
	}

	private IEnumerable<string> Lines(string value)
	{
		return value.Split(new[] { Environment.NewLine }, StringSplitOptions.None);
	}

	private string Xml(string value)
	{
		return value.Replace("<", "&lt;").Replace(">", "&gt;");
	}

	private string List(IEnumerable<string> items)
	{
		return List(null, items);
	}

	private string List(string prefix, IEnumerable<string> items, string suffix = null)
	{
		return string.Join(", ", items.Select(i => prefix + i + suffix));
	}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
