namespace Raider.Sql.Metadata
{
	/// <summary>
	///     <para>
	///         Indicates when a value for a property will be generated by the database.
	///     </para>
	/// </summary>
	public enum ValueGenerated
	{
		/// <summary>
		///     A value is never generated by the database.
		/// </summary>
		Never = 0,

		/// <summary>
		///     A value is generated by the database when an entity is first added to the database. The most common
		///     scenario for this is generated primary key values.
		/// </summary>
		OnAdd = 1,

		/// <summary>
		///     No value is generated when the entity is first added to the database, but a value will be read
		///     from the database whenever the entity is subsequently updated.
		/// </summary>
		OnUpdate = 2,

		/// <summary>
		///     A value is read from the database when the entity is first added and whenever the entity
		///     is subsequently updated. This is typically used for computed columns and scenarios such as
		///     rowversions, timestamps, etc.
		/// </summary>
		OnAddOrUpdate = OnAdd | OnUpdate
	}
}
